### ISSUE TITLE
Add a existingSecret option for the MongoDB Connection String

### ISSUE THREAD

**Issue by victorgetz** [Cognigy/cognigy-ai-helm-chart#5]
Currently for every microservice you create its own MongoDB Connection Kubernetes Secret.
The problem is: You can not set the value of this secret since it is auto created with randAlphaNum. 
If the secret gets deleted you have a problem.

I searched for a way to set the environment variables which maybe overwrites it but i did not find anything.

In my opinion we have 2 choices:
- ENV Variables (but i don't know which ones maybe they don't even exists)
- wrap the secret with a if condition like (serviceAlexaManagement.database.existingSecret) is present then don't create one

**Comment by victorgetz** [comment]
After closer look it would be the best to be able to set the password and thats it.

dict "pw" (randAlphaNum 24) should be replaced with dict "pw" $mongoDBPassword

and replace this stuff with range otherwise it is a nightmare to maintain it

```yaml
{{- range $serviceName,$serviceValues := .Values.services}}
apiVersion: v1
kind: Secret
metadata:
  name: $serviceName
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  connection-string: "{{- include "connectionString.mongodb" (dict "pw" $serviceValues.mongoDB.password "serviceName" "service-trainer" "mongodbHosts" $.Values.cognigy.mongodb.hosts) | b64enc }}"
{{- end}}

```
